### ISSUE TITLE
Required field in allOf reference does not get enforced

### ISSUE THREAD

**Issue by ugexe** [croservices/openapi-schema-validate#7]
[This test](https://github.com/ugexe/Perl6-App--OpenAPI--META6Validator/blob/24a98472d9deb855cad6c74d28f825717a0883a8/t/routes-validate.t#L30-L37) fails, but I don't think it should.

child reference with required field "name" -- https://github.com/ugexe/Perl6-App--OpenAPI--META6Validator/blob/24a98472d9deb855cad6c74d28f825717a0883a8/resources/openapi.json#L175-L179

parent which uses allOf with the reference -- https://github.com/ugexe/Perl6-App--OpenAPI--META6Validator/blob/24a98472d9deb855cad6c74d28f825717a0883a8/resources/openapi.json#L46-L50

**Comment by Altai-man** [comment]
Temporarily blocked by https://github.com/croservices/cro-openapi-routes-from-definition/issues/10
I'll look at this using latest later.

**Comment by Altai-man** [comment]
I know it has been two years ago, but...

With everything on latest I cannot reproduce it anymore:

```
➜  Perl6-App--OpenAPI--META6Validator git:(master) raku -Ilib -I../openapi-schema-validate/ t/routes-validate.t
# Subtest: POST /validate
    ok 1 - Status is acceptable
    ok 2 - Content type is recognized as a JSON one
    ok 3 - Body is acceptable
    1..3
ok 1 - POST /validate
# Subtest: POST /validate
Request to /validate failed validation: validation of 'application/json' schema failed at root/allOf/properties/resources/2: Not an array:Hash
    ok 1 - Status is acceptable
    1..1
ok 2 - POST /validate
# Subtest: POST /validate
Request to /validate failed validation: validation of 'application/json' schema failed at root/allOf/1: Object does not have required property: "name"
    ok 1 - Status is acceptable
    1..1
ok 3 - POST /validate
1..3
```

If it is still at least somehow relevant, can you please check it?

**Comment by ugexe** [comment]
Can confirm test passes now
